[server_http_main]
service_name = "main"
bind_addr_http = ":80"
read_timeout = 10 # seconds
write_timeout = 10 # seconds
protocol = "http"

[logger]
log_level = "debug"
log_path = "logs/api/prod/"

[database_params]
max_open_cons = 100
