//go:build ignore
// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/mailru/easyjson/gen"

	pkg "db-performance-project/internal/forum/delivery/models"
)

func main() {
	g := gen.NewGenerator("getthreads_easyjson.go")
	g.SetPkg("models", "db-performance-project/internal/forum/delivery/models")
	g.DisallowUnknownFields()
	g.Add(pkg.EasyJSON_exporter_ForumGetThreadsResponse(nil))
	g.Add(pkg.EasyJSON_exporter_ThreadsList(nil))
	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
